public class funcionario {
    public String nome;
    public String rg;
    public String cpf;
    public string celular;
    public String cargo;
    public Decimal salario;
    
    public Funcionario(String nome,String rg,String cpf,String cargo,Decimal salario){
        this.nome = nome;
        this.rg = rg;
        this.cpf = cpf;
        this.celular = celular;
        this.cargo = cargo;
        this.salario = salario;
    }
}
